### ISSUE TITLE
scIB-R-integration environment has R version 3.6.1 but Seurat depends on R version >=4.0

### ISSUE THREAD

**Issue by rogershijin** [theislab/scib#239]
I get the error `package ‘Seurat’ is not available (for R version 3.6.1)` when trying to install, is there a way to get around this?  Thanks!

**Comment by LuckyMD** [comment]
Hey! I’m pretty sure there is a version of Seurat that is compatible with R 3.6.1. We were using Seurat 3.1.1 and 3.0.2 in the benchmark i believe. Could you install an older version of Seurat in the environment? Otherwise, we are just working on an updated environment for further use of the pipeline in the [scib-pipeline](https://github.com/theislab/scib-pipeline) repo in a PR as well. More installation instructions are there as well. Maybe check that out to see if that helps?

**Comment by rogershijin** [comment]
Thanks @LuckyMD! Was able to install Seurat 3.2.0 by installing old versions of rsvd (0.9) and spatstat (1.64-1).
