### ISSUE TITLE
scaling per batch, low number of cells 

### ISSUE THREAD

**Issue by jayypaul** [theislab/scib#321]
Hi all, 

I'm not sure if this issue should go here, but I wanted to ask any problems you may foresee when scaling per batch, and the number of cells per batch varies considerably. For instance, I have about 30 samples that I want to integrate, and the number of cells varies from: 2500 - 30 cells. I'm integrating with harmony, and utilizing the scib framework to assess/improve my integration results. I'm getting what I would expect to be good results, but unsure if it could be better or if there is something I'm not aware of.

Any help would be appreciated, or if you could let me know where I could post a question like this.

Thanks!

**Comment by LuckyMD** [comment]
Hi @jayypaul,

We haven't tested how scaling affects different batch sizes. We do find that for most methods scaling does not necessarily improve the overall integration performance as it shifts the integration toward stronger batch effect removal, but weakens the conservation of biological variation.

In general I would assume that with 30 cells per batch, scaling might not be the most important thing to worry about. It is probably difficult to discern batch from biological variation in such a small batch as there will not be as good a representation of different cell types in so few cells. This sounds like a challenge for any data integration approach (not just for scaling). I would assume that DL-based methods might struggle most with so few cells from which to learn the batch effect... Harmony might be a good shout (of scanorama, FastMNN...)

**Comment by LuckyMD** [comment]
Please re-open the issue if this does not address your question.

**Comment by jayypaul** [comment]
Thanks for the detailed answer, it was very helpful! Sounds like I should test with or without scaling =)

One follow up question about your comment, however; doesn't PCA require the data to be scaled (i.e. Z scored)?? I'm unsure about all the ins/outs of PCA , so this topic is actually something I've been taking for granted more or less and just running the pipeline as described on the tutorials.

**Comment by LuckyMD** [comment]
In classical ML applications, PCA is usually run on scaled, zero-centered data, yes. In single-cell applications it is also always zero-centered as otherwise the first component would just capture the mean expression level differences. Whether or not to scale your features will depend on whether you want all genes to have an equal contribution to the embedding or whether you are okay with more highly expressed genes (and therefore genes with higher variance) to contribute more to the embedding. If you assume that expression levels do convey some sort of feature relevance, then this might be useful.

**Comment by jayypaul** [comment]
Much appreciated LuckyMD!
