### ISSUE TITLE
 Normalize:  could not find function "sizeFactors"

### ISSUE THREAD

**Issue by Mari123i** [theislab/scib#331]
Hello,

I have a dataset to normalize and when using normalize from scib I get the following error:

```
RRuntimeError: Error in sizeFactors(computeSumFactors(SingleCellExperiment(list(counts = data_mat)),  : 
could not find function "sizeFactors"
```

Versions:
scib                          1.0.3
scanpy                        1.9.1
anndata                       0.8.0
anndata2ri                    1.0.6

Any tips on where this is coming from are very much apprechiated.

**Comment by mumichae** [comment]
Hi, thanks for pointing that out.

You are missing the R package [`scran`](https://bioconductor.org/packages/release/bioc/html/scran.html) for that function to work properly. We haven't addressed it in the documentation yet. Since R methods can't be managed by python installers, you need to install `scran` manually to the R instance that rpy2 accesses. Make sure you have Bioconductor installed as well.

We implemented `scran` as it was recommended by the [Current best practices in single-cell RNA-seq analysis](https://doi.org/10.15252/msb.20188746).
Depending on your problem, you might also want to consider using one of the simpler normalisation methods implemented in `scanpy`.
